# Generated by Django 2.2.3 on 2023-03-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(default='pending', max_length=30)),
            ],
        ),
    ]
