# Generated by Django 2.2.3 on 2023-03-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=30)),
                ('buyerid', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(max_length=30)),
                ('shippingaddress', models.CharField(max_length=60)),
                ('totalprice', models.IntegerField(max_length=30)),
            ],
        ),
    ]
