# Generated by Django 2.2.3 on 2023-03-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_cart_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='totalprice',
            field=models.IntegerField(),
        ),
    ]
