# Generated by Django 2.2.3 on 2023-03-31 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20230331_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='buyerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer_tb'),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_tb'),
        ),
    ]
