# Generated by Django 2.2.3 on 2023-03-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_category_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_tb',
            old_name='category',
            new_name='name',
        ),
    ]
